### ISSUE TITLE
Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by limahatzl** [danielstern/isomorphic-react#10]
Babel settings it needs update. But if you run jest tests you receive the errors: 

`Plugin/Preset files are not allowed to export objects, only functions. In /Users/xxx/xxx/isomorphic-react-jest/node_modules/babel-preset-react/lib/index.js`

`at createDescriptor (../../../../usr/local/lib/node_modules/jest-cli/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
          at Array.map (<anonymous>)
`

**Comment by sirlanceoflompoc** [comment]
I ran into this same issue. 
Fixed it through using a tool called babel-upgrade:
https://github.com/babel/babel-upgrade

run babel-upgrade --write 

to move this project from babel 6 to babel 7. 

Then update your babelrc file with these contents: 
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread"
  ]
}

**Comment by relfarias** [comment]
Yeap, I have done this upgrade to babel, then the tests now are ok to run but i still have problems to run the project with the setup to node server.
If you run npm run start-dev does ur project work fine? If yes, could you please let me know how did you set up the new scripts?

 "scripts": {
    "build": "cross-env webpack --config ./webpack.config.prod.babel.js",
    "postinstall": "npm install -g babel-cli@6.26.0 cross-env@5.0.5 webpack@3.6.0",
    "start": "npm run start-prod",
    "start-dev": "cross-env NODE_ENV=development babel-node server --useServerRender=true --useLiveData=false",
    "start-prod": "npm run build && cross-env NODE_ENV=production babel-node server --useServerRender=true --useLiveData=false",
    "test-dev": "jest --watch",
    "test-update-snapshots": "jest -u"
  },

**Comment by rodhall85** [comment]
Thanks @sirlanceoflompoc, your suggestion helped me. I sent @danielstern a PR to fix it.

**Comment by kinowarrior** [comment]
Unclear why you merged this into `master` but didn't merge it into the `jest` branch which is where it is needed! As such, the `jest` branch is still broken...

[Here is what needs to be replaced](https://github.com/danielstern/isomorphic-react/commit/c31fb21b301ad14d4063689930d6dbc5b612c2b3) for anyone reading this in same situation.

**Comment by danielstern** [comment]
@kinowarrior Would be happy to see a PR for merging this into the Jest branch
